# Generated by Django 4.2.1 on 2023-05-23 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField(max_length=5000)),
                ('data_publicacao', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField(max_length=5000)),
                ('data_publicacao', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('posts', models.ManyToManyField(related_name='Posts', to='core.post')),
            ],
        ),
    ]
